---
- name: Create borgmatic directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0750"
    owner: root
    path: /etc/borgmatic.d
    state: directory
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  register: borgmatic_config
  ansible.builtin.template:
    dest: /etc/borgmatic.d/config.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Add borgmatic backup & prune job
  when: borgmatic_config is not failed
  become: true
  ansible.builtin.cron:
    day: "*"
    hour: "*/6"
    job: borgmatic create prune compact -v -1
    minute: "15"
    month: "*"
    name: borgmatic create + prune
    user: root
    weekday: "*"
