---
- name: Reload nfs exports
  become: true
  ansible.builtin.command:
    cmd: exportfs -ra
  changed_when: true
- name: Restart nfs-idmapd
  become: true
  ansible.builtin.systemd:
    name: nfs-idmapd.service
    state: restarted
