---
- name: Set up arch box
  hosts: all
  roles:
    - system
    - role: disks
      when: "'vm' not in group_names and 'pi' not in group_names"
    - editor
#   - mounts
    - backups
#   - containers
    - terminal
    - role: artis3n.tailscale.machine
      when: "'production' in group_names"
      tags: tailscale
    - notifications
    - file_manager
#   - reverse_proxy
    - drift_management
    - role: datasets
      tags:
        - zfs
        - after-zfs
    - role: exports
      tags:
        - nfs
        - after-zfs
    - role: nt_file_server
      tags:
        - samba
        - after-zfs
      become: true
  tasks:
    # I canot disable the "Beelink Mini PC, ME Pro 2" speaker in the BIOS
    # Until I get the soldering iron out, this will have to do
    - name: Create blacklist config for pcspkr
      become: true
      ansible.builtin.copy:
        dest: /etc/modprobe.d/nobeep.conf
        content: "blacklist pcspkr\n"
        owner: root
        group: root
        mode: "0644"
    - name: Unload pcspkr module now
      become: true
      community.general.modprobe:
        name: pcspkr
        state: absent
