---
roles:
  - name: persist_journald
    src: https://github.com/cisagov/ansible-role-persist-journald
    version: v3.1.0
collections:
  - name: community.general
    version: "13.1.0"
  - name: artis3n.tailscale
    version: "1.2.1"
  - name: containers.podman
    version: "1.20.2"
  - name: community.crypto
    version: "3.2.2"
  - name: community.libvirt
    version: "2.3.0"
  - name: vladgh.samba
    version: "3.5.6"
