---
roles:
  - name: persist_journald
    src: https://github.com/cisagov/ansible-role-persist-journald
    version: v3.0.0
collections:
  - name: community.general
    version: "12.2.0"
  - name: artis3n.tailscale
    version: "1.2.0"
  - name: containers.podman
    version: "1.19.0"
  - name: community.crypto
    version: "3.1.1"
  - name: kewlfft.aur
    version: "0.13.0"
  - name: vladgh.samba
    version: "3.5.6"
