---
aur_packages:
  - name: python-rtslib-fb
    commit: 16d2c26cfab4a5ed2467fa4e81adb7462bd4e9df
  - name: targetcli-fb
    commit: 083f4b0a579c4758c039bcb8cd092254cda11b2a
enabled_services:
  - target.service
iscsi_user: cluster
iscsi_home: /var/lib/cluster
