---
- name: Restart tailscaled
  become: true
  ansible.builtin.systemd:
    name: tailscaled.service
    state: restarted
- name: Reload caddy
  become: true
  ansible.builtin.systemd:
    name: caddy.service
    state: reloaded
