---
- name: Create export directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path | default(nfs_export_base + '/' + item.name) }}"
    state: directory
    owner: "{{ item.uid | default(nfs_default_uid) }}"
    group: "{{ item.gid | default(nfs_default_gid) }}"
    mode: "0755"
  loop: "{{ nfs_exports }}"
  loop_control:
    label: "{{ item.name }}"
- name: Generate /etc/exports
  become: true
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Reload nfs exports
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/exports.yaml
    group: root
    mode: "0600"
    owner: root
    src: borgmatic.yaml.j2
