---
- name: Restart autofs
  become: true
  ansible.builtin.systemd:
    name: autofs
    state: restarted
- name: Clear nfsidmap cache
  become: true
  ansible.builtin.command:
    cmd: nfsidmap -c
  changed_when: true
