---
enabled_services:
  - zfs-import-cache.service
  - zfs-import.target
  - zfs-mount.service
  - zfs.target
  - zfs-zed.service
  - zfs-auto-snapshot-hourly.timer
  - zfs-auto-snapshot-daily.timer
  - zfs-auto-snapshot-weekly.timer
  - "zfs-scrub-monthly@{{ zpool_name }}.timer"
zfs_datasets: []
