---
aur_packages:
  - name: zfs-auto-snapshot
    commit: a54004c6f84cbb86bbbd5b54aa312794b22e2f11
enabled_services:
  - zfs-import-cache.service
  - zfs-import.target
  - zfs-mount.service
  - zfs.target
  - zfs-zed.service
  - zfs-auto-snapshot-hourly.timer
  - zfs-auto-snapshot-daily.timer
  - zfs-auto-snapshot-weekly.timer
  - "zfs-scrub-monthly@{{ zpool_name }}.timer"
zfs_datasets: []
