---
- name: Configure NFSv4 idmapd
  become: true
  ansible.builtin.template:
    src: idmapd.conf.j2
    dest: /etc/idmapd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Clear nfsidmap cache
- name: Configure auto.master
  become: true
  ansible.builtin.template:
    src: auto.master.j2
    dest: /etc/autofs/auto.master
    owner: root
    group: root
    mode: "0600"
  notify: Restart autofs
- name: Configure auto.misc
  become: true
  ansible.builtin.template:
    src: auto.misc.j2
    dest: /etc/autofs/auto.misc
    owner: root
    group: root
    mode: "0600"
  notify: Restart autofs
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
