---
domain_name: nas.internal
nfs_exports:
  - name: immich-upload
    options: "rw,sync,no_root_squash,mp"
    uid: 0
    gid: 0
    clients:
      - frontend.internal
  - name: immich-encoded-video
    options: "rw,sync,no_root_squash,mp"
    uid: 0
    gid: 0
    clients:
      - frontend.internal
  - name: karakeep-assets
    options: "rw,sync,no_root_squash,mp"
    uid: 0
    gid: 0
    clients:
      - frontend.internal
  - name: paperless-consume
    path: /srv/samba/paperless-consume
    options: "rw,sync,no_root_squash,mp"
    clients:
      - frontend.internal
  - name: homeassistant-backup
    options: "rw,sync,no_root_squash,mp"
    uid: 0
    gid: 0
    clients:
      - homeassistant.internal
  - name: beacon-backup
    options: "rw,sync,no_root_squash,mp"
    uid: 0
    gid: 0
    clients:
      - beacon.internal
  - name: nt-vm-backup
    options: "rw,sync,no_root_squash,mp"
    uid: 0
    gid: 0
    clients:
      - nt-hypervisor.internal
zfs_datasets:
  - name: tank/immich-upload
    properties:
      mountpoint: /srv/nfs/immich-upload
  - name: tank/immich-encoded-video
    properties:
      mountpoint: /srv/nfs/immich-encoded-video
  - name: tank/karakeep-assets
    properties:
      mountpoint: /srv/nfs/karakeep-assets
  - name: tank/homeassistant-backup
    properties:
      mountpoint: /srv/nfs/homeassistant-backup
  - name: tank/beacon-backup
    properties:
      mountpoint: /srv/nfs/beacon-backup
  - name: tank/nt-vm-backup
    properties:
      mountpoint: /srv/nfs/nt-vm-backup
      compression: zstd
      "com.sun:auto-snapshot": "false"
  - name: tank/ludusavi
    properties:
      mountpoint: /srv/samba/ludusavi
  - name: tank/gamepc-share
    properties:
      mountpoint: /srv/samba/gamepc-share
  - name: tank/laptop-pro-share
    properties:
      mountpoint: /srv/samba/laptop-pro-share
  - name: tank/paperless-consume
    properties:
      mountpoint: /srv/samba/paperless-consume
  - name: tank/timemachine-laptop-pro
    properties:
      mountpoint: /srv/samba/timemachine-laptop-pro
      quota: 2T
      xattr: sa
      "com.sun:auto-snapshot": "false"
samba_shares_root: /srv/samba
# Used the following article to tune samba:
# https://www.antoneliasson.se/journal/time-machine-compatible-samba-on-debian-buster/
samba_global_config_extras: |
  fruit:resource = xattr
  fruit:encoding = native
  fruit:copyfile = yes
  include = /etc/samba/extra-shares.conf
samba_shares:
  - name: ludusavi
    comment: Game save backups
    owner: "{{ username }}"
    group: "{{ group }}"
    directory_mode: "0755"
    valid_users: gamepc
    write_list: gamepc
    user: "{{ username }}"
  - name: gamepc-share
    comment: gamepc share
    owner: "{{ username }}"
    group: "{{ group }}"
    directory_mode: "0755"
    valid_users: gamepc
    write_list: gamepc
    user: "{{ username }}"
  - name: laptop-pro-share
    comment: laptop-pro share
    owner: "{{ username }}"
    group: "{{ group }}"
    directory_mode: "0755"
    valid_users: laptop_pro
    write_list: laptop_pro
    user: "{{ username }}"
  - name: paperless-consume
    comment: Paperless consume
    owner: "{{ username }}"
    group: "{{ group }}"
    directory_mode: "0755"
    valid_users: epson
    write_list: epson
    user: "{{ username }}"
  - name: timemachine-laptop-pro
    comment: Time Machine (laptop-pro)
    owner: laptop_pro
    group: laptop_pro
    directory_mode: "0700"
    valid_users: laptop_pro
    write_list: laptop_pro
    vfs_objects:
      - name: catia
      - name: fruit
        options:
          - name: time machine
            value: "yes"
          - name: time machine max size
            value: "2T"
      - name: streams_xattr
samba_users:
  - name: gamepc
    password: "{{ gamepc_smb_password }}"
  - name: epson
    password: "{{ epson_smb_password }}"
  - name: laptop_pro
    password: "{{ laptop_pro_smb_password }}"
gamepc_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/gamepc_smb_password') }}"
epson_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/epson_smb_password') }}"
laptop_pro_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/laptop_pro_smb_password') }}"
zpool_name: tank
zpool_disks:
  - "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/zfs-tank-disk1-path') }}"
  - "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/zfs-tank-disk2-path') }}"
zpool_key: "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/zfs-tank-key') }}"
# On boot, eth0/eth1 are the arbitrarily assigned network device names (different than post-boot)
# They seem to switch randomly between the two, and I'm not sure why
#
# If I assign one, it'll break if the other gets pulled
#
# This works, I don't care why
dropbear_ip_cmdline: "ip=:::::eth0:dhcp:ip=:::::eth1:dhcp"
borg_passphrase: "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/borg_passphrase') }}"
remote_borg_repo_path: "{{ lookup('community.general.passwordstore', 'Repositories/nas-infra/remote_borg_repo_path') }}"
