---
- name: Grant caddy user access to fetch Tailscale certificate
  become: true
  when: "'production' in group_names"
  tags: tailscale
  ansible.builtin.lineinfile:
    path: /etc/default/tailscaled
    regexp: "^TS_PERMIT_CERT_UID="
    line: "TS_PERMIT_CERT_UID=caddy"
  notify: Restart tailscaled
- name: Create Caddy conf.d directory
  become: true
  ansible.builtin.file:
    path: /etc/caddy/conf.d
    state: directory
    group: root
    mode: "0755"
    owner: root
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    group: caddy
    mode: "0640"
    owner: caddy
  notify: Restart caddy
