---
packages:
  - nfs-utils
enabled_services:
  - nfs-server.service
  - nfs-idmapd.service
nfs_export_base: /srv/nfs
nfs_default_uid: 1000
nfs_default_gid: 1000
nfs_idmap_domain: internal
nfs_exports: []
