---
packages:
  - base-devel
  - git
  - htop
  - rsync
  - curl
  - wget
  - openbsd-netcat
  - cronie
  - bash-completion
  - which
  - man-db
  - fail2ban
  - fastfetch
enabled_services:
  - sshd
  - cronie
  - man-db.timer
  - fail2ban
