---
- name: Create gamepc user
  become: true
  ansible.builtin.user:
    name: gamepc
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    password: "!"
    password_lock: true
- name: Create epson user
  become: true
  ansible.builtin.user:
    name: epson
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    password: "!"
    password_lock: true
- name: Create laptop_pro user
  become: true
  ansible.builtin.user:
    name: laptop_pro
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    password: "!"
    password_lock: true
- name: Ensure /srv/samba is owned by root
  become: true
  ansible.builtin.file:
    path: /srv/samba
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/shares.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
